name: "[Reusable] Test Variable Scoping"

on:
  workflow_call:
    inputs:
      input_value:
        type: string
        required: false
        default: bar

jobs:
  nested-debug:
    runs-on: ubuntu-latest
    env:
      LOCAL_GITHUB_EVENT_INPUT_VALUE: ${{ github.event.inputs.input_value }}
      LOCAL_INPUT_VALUE: ${{ inputs.input_value }}
    steps:
      - name: Print Variables
        run: |
          echo "env.LOCAL_GITHUB_EVENT_INPUT_VALUE: ${{ env.LOCAL_GITHUB_EVENT_INPUT_VALUE }}"
          echo "env.LOCAL_INPUT_VALUE: ${{ env.LOCAL_INPUT_VALUE }}"
          echo "inputs: ${{ toJSON(inputs) }}"
          echo "env: ${{ toJSON(env) }}"
