name: "Test Variable Scoping"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      choice_input:
        type: choice
        options:
          - foo
          - bar

env:
  GLOBAL_INPUT_VALUE: ${{ github.event.inputs.choice_input || 'bar' }}
  GLOBAL_FIXED_VALUE: bar

jobs:
  debug:
    runs-on: ubuntu-latest
    env:
      LOCAL_INPUT_VALUE: $GLOBAL_INPUT_VALUE
      LOCAL_FIXED_VALUE: $GLOBAL_FIXED_VALUE
      LOCAL_INPUT_VALUE_REF: ${{ github.env.GLOBAL_INPUT_VALUE }}
      LOCAL_NON_EXISTING_REF: ${{ github.env.GLOBAL_DOES_NOT_EXIST }}
      #LOCAL_INPUT_VALUE_ENV: ${{ env.GLOBAL_INPUT_VALUE }}
      #LOCAL_NON_EXISTING_ENV: ${{ env.GLOBAL_DOES_NOT_EXIST }}
    steps:
      - name: Print Variables
        run: |
          echo "github.env.GLOBAL_INPUT_VALUE: ${{ github.env.GLOBAL_INPUT_VALUE }}"
          echo "github.env.GLOBAL_FIXED_VALUE: ${{ github.env.GLOBAL_FIXED_VALUE }}"
          echo "github.event.inputs.choice_input: ${{ github.event.inputs.choice_input }}"
          echo "inputs.choice_input: ${{ inputs.choice_input }}"
          echo "env.GLOBAL_INPUT_VALUE: ${{ env.GLOBAL_INPUT_VALUE }}"
          echo "env.GLOBAL_FIXED_VALUE: ${{ env.GLOBAL_FIXED_VALUE }}"
          echo "env.LOCAL_INPUT_VALUE: ${{ env.LOCAL_INPUT_VALUE }}"
          echo "env.LOCAL_FIXED_VALUE: ${{ env.LOCAL_FIXED_VALUE }}"
          echo "env.LOCAL_INPUT_VALUE_REF: ${{ env.LOCAL_INPUT_VALUE_REF }}"
          echo "env.LOCAL_NON_EXISTING_REF: ${{ env.LOCAL_NON_EXISTING_REF }}"
          echo "inputs: ${{ toJSON(inputs) }}"
          echo "env: ${{ toJSON(env) }}"
